Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/ClassLength:
  Max: 1500
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 20
#AllCops:
#  Exclude: